# The URL the site will be built for
base_url = "https://altrecsys.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "academic-workshop"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
header_menu_name = "venues"

[[extra.menus.venues]]
name = "SIGIR 2026"
url = "/sigir2026/"

[extra.title]
title = "The AltRecSys Workshop on Alternative, Unexpected, and Critical Ideas in Recommendation"
# subtitles = ["A workshop at RecSys 2024 & 2026"]

[[extra.header_pages]]
name = "Home"
url = "/"

[[extra.header_pages]]
name = "RecSys 2026"
url = "/recsys26/"


[[extra.header_pages]]
name = "RecSys 2024"
url = "/recsys24/"

[[extra.buttons]]
name = "Home"
url = "/"

[[extra.buttons]]
name = "RecSys 2026"
url = "/recsys26/"


[[extra.buttons]]
name = "RecSys 2024"
url = "/recsys24/"
